# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jim/pix86

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jim/pix86

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jim/pix86/CMakeFiles /home/jim/pix86//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jim/pix86/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pix86

# Build rule for target.
pix86: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pix86
.PHONY : pix86

# fast build rule for target.
pix86/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/build
.PHONY : pix86/fast

#=============================================================================
# Target rules for targets named pix86_test

# Build rule for target.
pix86_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pix86_test
.PHONY : pix86_test

# fast build rule for target.
pix86_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/pix86_test.dir/build.make test/CMakeFiles/pix86_test.dir/build
.PHONY : pix86_test/fast

#=============================================================================
# Target rules for targets named mrr_vis

# Build rule for target.
mrr_vis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mrr_vis
.PHONY : mrr_vis

# fast build rule for target.
mrr_vis/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/mrr_vis.dir/build.make test/CMakeFiles/mrr_vis.dir/build
.PHONY : mrr_vis/fast

src/cpu.o: src/cpu.cc.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/cpu.cc.o
.PHONY : src/cpu.cc.o

src/cpu.i: src/cpu.cc.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/cpu.cc.i
.PHONY : src/cpu.cc.i

src/cpu.s: src/cpu.cc.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/cpu.cc.s
.PHONY : src/cpu.cc.s

src/decoder.o: src/decoder.cc.o
.PHONY : src/decoder.o

# target to build an object file
src/decoder.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/decoder.cc.o
.PHONY : src/decoder.cc.o

src/decoder.i: src/decoder.cc.i
.PHONY : src/decoder.i

# target to preprocess a source file
src/decoder.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/decoder.cc.i
.PHONY : src/decoder.cc.i

src/decoder.s: src/decoder.cc.s
.PHONY : src/decoder.s

# target to generate assembly for a file
src/decoder.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/decoder.cc.s
.PHONY : src/decoder.cc.s

src/executor.o: src/executor.cc.o
.PHONY : src/executor.o

# target to build an object file
src/executor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/executor.cc.o
.PHONY : src/executor.cc.o

src/executor.i: src/executor.cc.i
.PHONY : src/executor.i

# target to preprocess a source file
src/executor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/executor.cc.i
.PHONY : src/executor.cc.i

src/executor.s: src/executor.cc.s
.PHONY : src/executor.s

# target to generate assembly for a file
src/executor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/executor.cc.s
.PHONY : src/executor.cc.s

src/flags.o: src/flags.cc.o
.PHONY : src/flags.o

# target to build an object file
src/flags.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/flags.cc.o
.PHONY : src/flags.cc.o

src/flags.i: src/flags.cc.i
.PHONY : src/flags.i

# target to preprocess a source file
src/flags.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/flags.cc.i
.PHONY : src/flags.cc.i

src/flags.s: src/flags.cc.s
.PHONY : src/flags.s

# target to generate assembly for a file
src/flags.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/flags.cc.s
.PHONY : src/flags.cc.s

src/fpu.o: src/fpu.cc.o
.PHONY : src/fpu.o

# target to build an object file
src/fpu.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/fpu.cc.o
.PHONY : src/fpu.cc.o

src/fpu.i: src/fpu.cc.i
.PHONY : src/fpu.i

# target to preprocess a source file
src/fpu.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/fpu.cc.i
.PHONY : src/fpu.cc.i

src/fpu.s: src/fpu.cc.s
.PHONY : src/fpu.s

# target to generate assembly for a file
src/fpu.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/fpu.cc.s
.PHONY : src/fpu.cc.s

src/generic_reference.o: src/generic_reference.cc.o
.PHONY : src/generic_reference.o

# target to build an object file
src/generic_reference.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/generic_reference.cc.o
.PHONY : src/generic_reference.cc.o

src/generic_reference.i: src/generic_reference.cc.i
.PHONY : src/generic_reference.i

# target to preprocess a source file
src/generic_reference.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/generic_reference.cc.i
.PHONY : src/generic_reference.cc.i

src/generic_reference.s: src/generic_reference.cc.s
.PHONY : src/generic_reference.s

# target to generate assembly for a file
src/generic_reference.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/generic_reference.cc.s
.PHONY : src/generic_reference.cc.s

src/memory.o: src/memory.cc.o
.PHONY : src/memory.o

# target to build an object file
src/memory.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/memory.cc.o
.PHONY : src/memory.cc.o

src/memory.i: src/memory.cc.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/memory.cc.i
.PHONY : src/memory.cc.i

src/memory.s: src/memory.cc.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/memory.cc.s
.PHONY : src/memory.cc.s

src/mmx.o: src/mmx.cc.o
.PHONY : src/mmx.o

# target to build an object file
src/mmx.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/mmx.cc.o
.PHONY : src/mmx.cc.o

src/mmx.i: src/mmx.cc.i
.PHONY : src/mmx.i

# target to preprocess a source file
src/mmx.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/mmx.cc.i
.PHONY : src/mmx.cc.i

src/mmx.s: src/mmx.cc.s
.PHONY : src/mmx.s

# target to generate assembly for a file
src/mmx.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/mmx.cc.s
.PHONY : src/mmx.cc.s

src/pix86.o: src/pix86.cc.o
.PHONY : src/pix86.o

# target to build an object file
src/pix86.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/pix86.cc.o
.PHONY : src/pix86.cc.o

src/pix86.i: src/pix86.cc.i
.PHONY : src/pix86.i

# target to preprocess a source file
src/pix86.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/pix86.cc.i
.PHONY : src/pix86.cc.i

src/pix86.s: src/pix86.cc.s
.PHONY : src/pix86.s

# target to generate assembly for a file
src/pix86.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/pix86.cc.s
.PHONY : src/pix86.cc.s

src/sse.o: src/sse.cc.o
.PHONY : src/sse.o

# target to build an object file
src/sse.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/sse.cc.o
.PHONY : src/sse.cc.o

src/sse.i: src/sse.cc.i
.PHONY : src/sse.i

# target to preprocess a source file
src/sse.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/sse.cc.i
.PHONY : src/sse.cc.i

src/sse.s: src/sse.cc.s
.PHONY : src/sse.s

# target to generate assembly for a file
src/sse.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/sse.cc.s
.PHONY : src/sse.cc.s

src/util.o: src/util.cc.o
.PHONY : src/util.o

# target to build an object file
src/util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/util.cc.o
.PHONY : src/util.cc.o

src/util.i: src/util.cc.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/util.cc.i
.PHONY : src/util.cc.i

src/util.s: src/util.cc.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pix86.dir/build.make CMakeFiles/pix86.dir/src/util.cc.s
.PHONY : src/util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mrr_vis"
	@echo "... pix86"
	@echo "... pix86_test"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/decoder.o"
	@echo "... src/decoder.i"
	@echo "... src/decoder.s"
	@echo "... src/executor.o"
	@echo "... src/executor.i"
	@echo "... src/executor.s"
	@echo "... src/flags.o"
	@echo "... src/flags.i"
	@echo "... src/flags.s"
	@echo "... src/fpu.o"
	@echo "... src/fpu.i"
	@echo "... src/fpu.s"
	@echo "... src/generic_reference.o"
	@echo "... src/generic_reference.i"
	@echo "... src/generic_reference.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/mmx.o"
	@echo "... src/mmx.i"
	@echo "... src/mmx.s"
	@echo "... src/pix86.o"
	@echo "... src/pix86.i"
	@echo "... src/pix86.s"
	@echo "... src/sse.o"
	@echo "... src/sse.i"
	@echo "... src/sse.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

